services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - "5400:5432"
